-- Database: mijigym

-- DROP DATABASE mijigym;
-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.

------ Drop databse and terminate all connections
REVOKE CONNECT ON DATABASE mijigym FROM public;
SELECT pid, pg_terminate_backend(pid) 
FROM pg_stat_activity 
WHERE datname = current_database() AND pid <> pg_backend_pid();
------ Update existing trainee
UPDATE trainee
SET trainee_level_id = 1,
    trainee_frequency_id = 2,
    trainee_objective_id = 3
WHERE trainee_email = 'jose.guambo@udla.edu.ec';

------- Create new user 
INSERT INTO trainee (trainee_name, trainee_email)
	VALUES ('Luis Cardoso', 'luis@cardoso.com');

------- Create new user with all the parameters
INSERT INTO trainee (trainee_name,trainee_age,trainee_gender,trainee_email,trainee_frequency_id,trainee_level_id,trainee_objective_id )
	VALUES ('jose guambo', 26, 'hombre','jose@guambo.com',3,3,1 );










