-- Database: mijigym

-- DROP DATABASE mijigym;
-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.

------ Drop databse and terminate all connections
REVOKE CONNECT ON DATABASE mijigym FROM public;
SELECT pid, pg_terminate_backend(pid) 
FROM pg_stat_activity 
WHERE datname = current_database() AND pid <> pg_backend_pid();
------ Update existing trainee
UPDATE trainee
SET trainee_level_id = 1,
    trainee_frequency_id = 2,
    trainee_objective_id = 3
WHERE trainee_email = 'jose.guambo@udla.edu.ec';

------- Create new user 
INSERT INTO trainee (trainee_name, trainee_email)
	VALUES ('Luis Cardoso', 'luis@cardoso.com');

------- Create new user with all the parameters
INSERT INTO trainee (trainee_name,trainee_age,trainee_gender,trainee_email,trainee_frequency_id,trainee_level_id,trainee_objective_id )
	VALUES ('jose guambo', 26, 'hombre','jose@guambo.com',3,3,1 );

-------- Query trainee_frequency_id from trainee_frequency_type
SELECT trainee_frequency_id  FROM trainee_frequency WHERE trainee_frequency_type = '5 dias por semana'

---------- update table

UPDATE recommendation
SET  recommendation_text = 'Estas en la época perfecta para la musculación. Si particularmente no practicas ningún deporte te recomiendo que le pongas una super énfasis a la hipertrofia (y no tanto a la fuerza), porque mejorará tu estética de manera increíble. Es genial porque tus niveles de testosterona en tu cuerpo son muy elevados, además de que podrás desarrollar madurez muscular.'
WHERE recommendation_type = 5 AND recommendation_number = 2

----------------  Select name of trainee and text of recommendation with trainee_id

SELECT trainee_name as name,
		recommendation_text as text
FROM
              trainee train
              INNER JOIN trainee_recommendation train_rec ON train_rec.trainee_id = train.trainee_id
              INNER JOIN recommendation rec ON train_rec.recommendation_id = rec.recommendation_id
Where train.trainee_id = (select trainee_id 
        from trainee
        order by trainee_id desc
        limit 1);

----------------- Count
SELECT *
from trainee_recommendation
order by trainee_recommendation DESC
limit 5





