-- Database: mijigym

-- DROP DATABASE mijigym;
-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.training_frequency
(
    "training_frequency_id" SERIAL,
    training_frequency_type text NOT NULL,
    PRIMARY KEY ("training_frequency_id")
);

CREATE TABLE public.trainee_level
(
    trainee_level_id SERIAL,
    trainee_level_type text NOT NULL,
    PRIMARY KEY (trainee_level_id)
);

CREATE TABLE public.trainee_objective
(
    trainee_objective_id SERIAL,
    trainee_objective_type text NOT NULL,
    PRIMARY KEY (trainee_objective_id)
);

CREATE TABLE public.trainee
(
    trainee_id SERIAL,
    trainee_name text NOT NULL,
    trainee_age integer ,
    trainee_gender text ,
    trainee_email text NOT NULL,
    training_frequency_id integer ,
    trainee_level_id integer ,
    trainee_objective_id integer ,
    PRIMARY KEY (trainee_id)
);

ALTER TABLE public.trainee
    ADD FOREIGN KEY (training_frequency_id)
    REFERENCES public.training_frequency ("training_frequency_id")
    NOT VALID;


ALTER TABLE public.trainee
    ADD FOREIGN KEY (trainee_level_id)
    REFERENCES public.trainee_level (trainee_level_id)
    NOT VALID;


ALTER TABLE public.trainee
    ADD FOREIGN KEY (trainee_objective_id)
    REFERENCES public.trainee_objective (trainee_objective_id)
    NOT VALID;

END;

INSERT INTO trainee_level (trainee_level_type)
	VALUES ('novato (0-1 años)');
INSERT INTO trainee_level (trainee_level_type)
	VALUES ('intermedio (1-3 años)');
INSERT INTO trainee_level (trainee_level_type)
	VALUES ('avanzado (más de 3 años)');

INSERT INTO trainee_objective (trainee_objective_type)
	VALUES ('Bajar de peso');
INSERT INTO trainee_objective (trainee_objective_type)
	VALUES ('Subir de peso');
INSERT INTO trainee_objective (trainee_objective_type)
	VALUES ('Mantener peso');
INSERT INTO training_frequency (training_frequency_type)
	VALUES ('3 dias por semana');
INSERT INTO training_frequency (training_frequency_type)
	VALUES ('4 dias por semana');
INSERT INTO training_frequency (training_frequency_type)
	VALUES ('5 dias por semana');

INSERT INTO trainee (trainee_name, trainee_email)
	VALUES ('José Guambo', 'jlguambo@gmail.com');
INSERT INTO trainee (trainee_name, trainee_email)
	VALUES ('Luis Cardoso', 'luis@cardoso.com');












